-- AlterTable
ALTER TABLE `user` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `updatedAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `firstName` VARCHAR(191) NOT NULL DEFAULT 'Prénom',
    MODIFY `lastName` VARCHAR(191) NOT NULL DEFAULT 'Nom';
